//! Spanish bodies for the legal pages (issue #1 sweep). The English `const`s stay exactly as
//! they are: 21 tests pin their claims, and the EN text remains the source the audit reads. Each
//! `*_ES` here is the translation the Spanish locale draws, picked by `i18n::is_es()` in
//! `Page::body`/`Page::title`/`Page::subtitle` - a static pick, never a build, same pattern as
//! the busy captions. The PRIVACY translation mirrors the English section by section; if the
//! English claim changes, its Spanish twin must change with it or it becomes a second document.

#[cfg(feature = "jellyfin")]
pub(crate) const PRIVACY_ES: &str = "RESPONSABLE DE LOS DATOS DE BUTACA\n\nQuien mantiene butaca solo responde de los datos que butaca guarda localmente en esta television.\n\nTU SERVIDOR JELLYFIN\n\nbutaca es un cliente independiente de Jellyfin. No existe un servicio central de cuentas de Jellyfin: para iniciar sesion, explorar y reproducir contenido, actualizar el progreso de visionado y usar las funciones del servidor, la app se comunica directamente con el servidor Jellyfin que tu indiques. Esas peticiones las gestiona ese servidor y quien lo opera. El desarrollador de butaca no las recibe.\n\nEN ESTA TELEVISION\n\nbutaca guarda la direccion de tu servidor Jellyfin, tu usuario y tu contrasena (en un fichero que solo la app puede leer), un identificador del dispositivo, tus elecciones de bibliotecas para el Inicio, tus busquedas recientes y tu preferencia de calidad de reproduccion. Tambien mantiene un pequeno registro local rotatorio y un registro local de errores para depuracion; ambos se quedan en esta television y solo se leen desde ella. butaca no envia nada: no hay informes de error, ni analitica, ni diagnosticos que salgan de la television, y nada de estos registros se transmite a ningun sitio. No mantiene ningun marcador propio de por donde ibas: la posicion de reproduccion la guarda tu servidor Jellyfin. Borrar todos los datos locales en Ajustes cierra la sesion y elimina los datos de butaca en esta television.\n\nAL DESINSTALAR\n\nQuitar butaca elimina la aplicacion, pero webOS no ofrece a una app ejecutar codigo mientras se desinstala, asi que lo guardado fuera del directorio de la app puede sobrevivir. Tu inicio de sesion se guarda alli a proposito, para que reinstalar no te cierre sesion. Usa Borrar todos los datos ANTES de desinstalar si no quieres dejar nada de butaca en esta television.\n\nCONTACTO\n\nPreguntas de privacidad: support@plxnative.com";
#[cfg(not(feature = "jellyfin"))]
pub(crate) const PRIVACY_ES: &str = "";

pub(crate) const OPEN_SOURCE_ES: &str = "butaca es software libre bajo licencia MIT, construido sobre el proyecto plx-native. Copyright (c) 2026 Gleb Linnik y contribuidores.\n\nEl paquete de la aplicacion incluye THIRD-PARTY-NOTICES.md, los textos completos de licencia y los avisos de fuentes. Entre los proyectos incluidos estan libcurl, SDL2, SDL2_ttf, nanosvg, zlib, jsmpeg, Inter, Noto Sans CJK, Feather, Heroicons, Material Icons y los crates de Rust usados por esta build.";

pub(crate) const FFMPEG_ES: &str = "Este software usa librerias del proyecto FFmpeg bajo LGPLv2.1. FFmpeg es copyright (c) de los desarrolladores de FFmpeg; butaca no es duena de FFmpeg.\n\nLas librerias de FFmpeg van sin modificar y se cargan dinamicamente, y pueden sustituirse por una build compatible de interfaz. El codigo fuente completo correspondiente de FFmpeg 9.0, la linea exacta de configure y el script de build se publican con cada release de plx-native.";

pub(crate) const SOURCE_ES: &str = "butaca se construye sobre el codigo fuente, materiales de release y scripts de build de plx-native, publicados en:\n\ngithub.com/GLinnik21/plx-native\n\nLos paquetes de fuente de cada release incluyen la fuente correspondiente de FFmpeg y el script usado para compilarla.";

pub(crate) const TRADEMARKS_ES: &str = "Jellyfin es un sistema multimedia de software libre desarrollado por el Proyecto Jellyfin.\n\nLG y webOS son marcas de LG Electronics Inc.\n\nbutaca es una aplicacion independiente y no oficial. No esta producida, respaldada ni afiliada al Proyecto Jellyfin ni a LG Electronics Inc.";

pub(crate) const CONTACT_ES: &str = "Las preguntas de privacidad pueden enviarse a support@plxnative.com.\n\nLas vulnerabilidades de seguridad pueden reportarse de forma privada en los GitHub Security Advisories de GLinnik21/plx-native. No incluyas contrasenas o tokens de Jellyfin, direcciones de servidores ni informacion personal de tus medios en un reporte.";
