#!/usr/bin/env python3
"""Read saved ABR device logs and print the transaction/plant tables, as markdown.

WHY THIS IS A TOOL. The first draft of `docs/measurements/p1-transaction-anatomy.md` had five
wrong numbers in its headline table -- not misread, but transcribed from a log that a later run
of the same case had already overwritten. Numbers hand-copied out of a terminal into a document
cannot be re-checked without redoing the run, and a measurement nobody can re-derive is an
anecdote. Every table in that document is generated by this script, so re-running it against the
same logs reproduces it exactly, and running it against new logs says so.

    tools/abr-tx-report.py <log-dir-or-files>...
    tools/abr-tx-report.py /tmp/abr-p1-logs --section cost

Reads `abr: tx`, `abr: sample` and `hls: segment` through `tests/run.py`'s own regexes, so a
format change breaks this the same way it breaks the harness -- and is caught by the contract
test in `tests/test_harness.py` rather than by a silently empty table here.
"""
import argparse, glob, importlib.util, os, statistics, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tests"))
import run                                                        # noqa: E402


def load_sweep():
    """`tools/abr-plant-sweep.py` owns the queue geometry; this never re-derives it."""
    spec = importlib.util.spec_from_file_location(
        "sweep", os.path.join(ROOT, "tools", "abr-plant-sweep.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def collect(paths):
    logs = []
    for p in paths:
        logs += sorted(glob.glob(os.path.join(p, "*.log"))) if os.path.isdir(p) else [p]
    tx, samples, segs = [], [], []
    for path in logs:
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
        case = os.path.basename(path)[:-4]
        for r in run.abr_transactions(lines):
            r["_case"] = case
            tx.append(r)
        for s in run.abr_samples(lines):
            s["_case"] = case
            samples.append(s)
        for s in run.hls_segments(lines):
            s["_case"] = case
            segs.append(s)
    return logs, tx, samples, segs


def thousands(n):
    return f"{n:,}".replace(",", " ")


def section_cost(tx, **_):
    sel = sorted((r for r in tx if r["feed_ms"] is not None and r["decided_ms"] is not None),
                 key=lambda r: -r["feed_ms"])
    print("| move | decided | feed | what `decided` used to report | feed's share |")
    print("|---|---:|---:|---:|---:|")
    for r in sel:
        total = r["decided_ms"] + r["feed_ms"]
        share = 100 * r["feed_ms"] // total if total else 0
        b = "**" if r["feed_ms"] > 19_000 else ""
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {b}{thousands(r['decided_ms'])}{b} | "
              f"{b}{thousands(r['feed_ms'])}{b} | {thousands(total)} | {b}{share}%{b} |")
    dec = [r["decided_ms"] for r in tx if r["decided_ms"] is not None]
    fed = [r["feed_ms"] for r in tx if r["feed_ms"] is not None]
    med = lambda v: sorted(v)[len(v) // 2]
    print(f"\nn = {len(tx)} transactions. **`decided` median {thousands(med(dec))} ms, "
          f"max {thousands(max(dec))} ms.** "
          f"**`feed` median {thousands(med(fed))} ms, max {thousands(max(fed))} ms.**")


def section_drain(tx, sweep, **_):
    """Does the reserve fall at exactly real time while the feed is blocked?"""
    print("| move | feed_ms | reserve drained | ratio |")
    print("|---|---:|---:|---:|")
    ratios = []
    for r in sorted((x for x in tx if x["to_kbps"] > x["from_kbps"] and x["feed_ms"]
                     and x["feed_ms"] > 1000 and x["buf_fed_ms"] is not None),
                    key=lambda x: -x["feed_ms"]):
        n = 2 if r["graded_ms"] is not None else 1
        drained = r["buf_decided_ms"] + n * sweep.D_MS - r["buf_fed_ms"]
        ratio = drained / r["feed_ms"]
        ratios.append(ratio)
        b = "**" if abs(ratio - 1) < 0.02 else ""
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {thousands(r['feed_ms'])} | "
              f"{thousands(drained)} | {b}{ratio:.2f}{b} |")
    if ratios:
        print(f"\nn = {len(ratios)}, ratio {min(ratios):.2f} .. {max(ratios):.2f}. "
              "1.00 is conservation: the feed blocks while playback keeps consuming at 1x.")


def section_ceiling(tx, sweep, **_):
    slack, bound = [], []
    for r in tx:
        if r["buf_fed_ms"] is None or r["buf_decided_ms"] is None:
            continue
        n = 2 if r["graded_ms"] is not None else 1
        unclamped = r["buf_decided_ms"] + n * sweep.D_MS
        bmax = sweep.b_max_ms(r["to_kbps"], sweep.AQ_VIDEO_BYTES, sweep.AQ_AUDIO_BYTES,
                              sweep.FEED_AHEAD_MS, sweep.AUDIO_SLACK_MS)
        (bound if unclamped > bmax else slack).append(
            (r, r["buf_fed_ms"] - min(unclamped, bmax), bmax))
    print(f"* **Ceiling slack (n = {len(slack)}):** errors "
          f"{sorted(e for _, e, _ in slack)}")
    if bound:
        errs = [e for _, e, _ in bound]
        rel = [100.0 * e / b for _, e, b in bound]
        print(f"* **Ceiling binding (n = {len(bound)}):** {min(errs):+} ms to {max(errs):+} ms "
              f"({min(rel):+.1f}% to {max(rel):+.1f}%); "
              f"{sum(1 for e in errs if e < 0)} of {len(errs)} negative.")
    print("\n| move | feed_ms | buf_fed | B_max(new) | ratio |")
    print("|---|---:|---:|---:|---:|")
    for r, _, bmax in sorted(bound, key=lambda x: -(x[0]["feed_ms"] or 0)):
        if r["feed_ms"] is None or r["feed_ms"] < 1000:
            continue
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {thousands(r['feed_ms'])} | "
              f"{thousands(r['buf_fed_ms'])} | {thousands(bmax)} | "
              f"{r['buf_fed_ms'] / bmax:.2f}x |")


def section_control(tx, **_):
    med = lambda v: sorted(v)[len(v) // 2]
    for name in ("prime_ms", "master_ms", "media_ms", "control_ms"):
        v = [r[name] for r in tx if r[name] is not None]
        if v:
            print(f"* `{name[:-3]}`: median {med(v)} ms, {min(v)}-{max(v)} ms, n={len(v)}")


def section_rates(samples, sweep, **_):
    byrung = {}
    for s in samples:
        byrung.setdefault(s["current_kbps"], []).append(s["media_kbps"])
    print("| rung | n | median kbps | min | max | max/min |")
    print("|---:|---:|---:|---:|---:|---:|")
    for rung in sorted(byrung):
        v = byrung[rung]
        spread = max(v) / min(v) if min(v) else 0
        b = "**" if abs(spread - 1) < 1e-9 else ""
        print(f"| {rung} | {len(v)} | {thousands(int(statistics.median(v)))} | "
              f"{thousands(min(v))} | {thousands(max(v))} | {b}{spread:.2f}{b} |")
    ratios = [statistics.median(byrung[r]) / r for r in byrung]
    print(f"\nn = {len(samples)} samples over {len(byrung)} rungs. "
          f"delivered/requested {min(ratios):.2f}x .. {max(ratios):.2f}x "
          f"({max(ratios) / min(ratios):.1f}x span).")


def section_fit(segs, **_):
    """Fit `A = O0 + bytes * tau` and report what the corpus can actually identify.

    The board's R7: the original n=366 fit was TEN data points, because `bytes` was an exact
    function of `rung` -- one fixture file answered every sequence number. An OLS standard error
    computed over 366 rows is then a fiction, so this reports the CLUSTER count beside it and a
    cluster-robust standard error, clustering on the byte size itself. If the two SEs are far
    apart, the naive one is measuring repetition rather than evidence.
    """
    import math
    rows = [(s["bytes"], s["total_ms"]) for s in segs
            if s.get("bytes") and s.get("total_ms")]
    if len(rows) < 3:
        print("not enough segments to fit"); return
    n = len(rows)
    clusters = {}
    for b, a in rows:
        clusters.setdefault(b, []).append(a)
    mx = sum(b for b, _ in rows) / n
    my = sum(a for _, a in rows) / n
    sxx = sum((b - mx) ** 2 for b, _ in rows)
    if sxx == 0:
        print("every segment is the same size — nothing to fit"); return
    tau = sum((b - mx) * (a - my) for b, a in rows) / sxx
    o0 = my - tau * mx
    resid = [(a - (o0 + tau * b)) for b, a in rows]
    dof = max(1, n - 2)
    s2 = sum(r * r for r in resid) / dof
    se_naive = math.sqrt(s2 / sxx)
    # Cluster-robust (CR0), clustering on byte size: sum of per-cluster score outer products.
    meat = 0.0
    for b, group in clusters.items():
        gi = sum((b - mx) * (a - (o0 + tau * b)) for a in group)
        meat += gi * gi
    se_cluster = math.sqrt(meat) / sxx if sxx else float("inf")
    print(f"* n = {n} segments in **{len(clusters)} distinct byte sizes** "
          f"(the effective sample for this fit)")
    print(f"* `tau` = {tau * 1e6:.2f} ns/byte, `O0` = {o0:.2f} ms")
    print(f"* SE(tau): naive {se_naive * 1e6:.2f} ns/byte, "
          f"cluster-robust {se_cluster * 1e6:.2f} ns/byte "
          f"({se_cluster / se_naive:.2f}x wider)" if se_naive else "")
    if tau > 0:
        print(f"* implied demux+link capacity `1/tau` = {8 / (tau * 1000):.1f} Mbit/s")
    else:
        print("* **tau is NEGATIVE** — more bytes taking less time, which is not physical. The "
              "corpus does not identify this model; it is not a slow link, it is no signal.")
    if abs(tau) < se_cluster:
        print("* **tau is inside its own robust standard error**, so it is not distinguishable "
              "from zero at any conventional level.")
    if len(clusters) < 30:
        print(f"* CAVEAT: {len(clusters)} clusters. CR0 is biased DOWNWARD in small-cluster "
              "samples, so the robust SE above is optimistic — the true uncertainty is worse "
              "than printed, not better.")
    print(f"* byte range {min(b for b, _ in rows):,} .. {max(b for b, _ in rows):,} "
          f"({max(b for b, _ in rows) / max(1, min(b for b, _ in rows)):.1f}x)".replace(",", " "))


def section_ratios(samples, **_):
    """MEASURED byte ratio between adjacent rungs, against the ratio their NAMES imply.

    Board finding R1: the admission rule scored 9/23 coverage against a nominal 0.90, and all 14
    misses were unsafe, because it used `R_t / R_i` -- the CATALOG rates -- while delivered over
    nominal spanned 2.4x. The rule needs measured per-rung sizes. This is where they come from,
    and the `error` column is what the nominal form would have been wrong by on each step.
    """
    import statistics
    byrung = {}
    for s in samples:
        byrung.setdefault(s["current_kbps"], []).append(s["media_kbps"])
    rungs = sorted(byrung)
    if len(rungs) < 2:
        print("fewer than two rungs observed — no adjacent pair to measure"); return
    print("| step | measured ratio | nominal ratio | error |")
    print("|---|---:|---:|---:|")
    worst = 1.0
    for lo, hi in zip(rungs, rungs[1:]):
        m = statistics.median(byrung[hi]) / statistics.median(byrung[lo])
        nom = hi / lo
        err = m / nom
        worst = max(worst, max(err, 1 / err))
        flag = "**" if abs(err - 1) > 0.10 else ""
        print(f"| {lo} -> {hi} | {m:.3f}x | {nom:.3f}x | {flag}{err:.3f}x{flag} |")
    print(f"\nWorst disagreement between measured and nominal: **{worst:.2f}x**. Anything above "
          "1.10x is a step where an admission rule built on catalog rates is materially wrong "
          "about how much bigger the next rung's segments are.")


# chi-square 0.95 critical values for 1..10 degrees of freedom. Hard-coded because this tool has
# no scipy and a wrong critical value is worse than none -- these are the only ones it needs.
CHI2_95 = {1: 3.84, 2: 5.99, 3: 7.81, 4: 9.49, 5: 11.07,
           6: 12.59, 7: 14.07, 8: 15.51, 9: 16.92, 10: 18.31}


def section_acf(segs, **_):
    """Serial dependence in the acquisition series, PER RUNG, with an effective-sample correction.

    This replaces the plan's coverage gate, which the board (R9) showed cannot fail on this
    corpus -- every window length 3..29 passes, and detecting the dependence it exists to detect
    would need about 104 hours of playback. An acf and a Ljung-Box statistic report the same
    property directly and can be read at any sample size, so long as what is reported is the
    statistic and not a verdict dressed up as one.

    WHY IT MATTERS: the order-statistic bound P(A_(n+1) > A_(n+1-k)) = k/(n+1) is exact under
    EXCHANGEABILITY. Positive autocorrelation breaks it in the unsafe direction, because
    consecutive acquisitions are then more alike than independent draws and the observed maximum
    understates the tail. `n_eff = n(1-rho)/(1+rho)` is the variance-of-the-mean heuristic, and it
    is a heuristic -- it is reported so the ratio is visible, never to be silently substituted for
    n in a bound.
    """
    import math
    def stats(series):
        n = len(series)
        mean = sum(series) / n
        var = sum((x - mean) ** 2 for x in series)
        if var == 0:
            return None
        rho = [sum((series[i] - mean) * (series[i + k] - mean) for i in range(n - k)) / var
               for k in range(1, 6)]
        q = n * (n + 2) * sum(r * r / (n - k - 1) for k, r in enumerate(rho) if n - k - 1 > 0)
        n_eff = n * (1 - rho[0]) / (1 + rho[0]) if rho[0] > -1 else float("nan")
        return rho[0], q, n_eff

    byrung, bytau = {}, {}
    for s in segs:
        case = s.get("_case", "?")
        byrung.setdefault(case, []).append(s["total_ms"])
        if s.get("bytes"):
            # The tau form: MILLISECONDS PER BYTE. A rung change moves `total_ms` because the
            # segments got bigger, and that level shift reads as autocorrelation in A while saying
            # nothing about link memory. Dividing it out is the board's R3 claim -- that tau is a
            # property of the link and the SoC rather than of the rung, so a tau window survives a
            # commit -- and this is the test of it.
            bytau.setdefault(case, []).append(s["total_ms"] / s["bytes"])
    print("| series | n | rho(A) | Q(A) | rho(tau) | Q(tau) | n_eff(tau) | verdict |")
    print("|---|---:|---:|---:|---:|---:|---:|---|")
    for name, series in sorted(byrung.items()):
        n = len(series)
        if n < 12:
            continue
        a, tv = stats(series), stats(bytau.get(name, []))
        if a and tv:
            crit = CHI2_95[5]
            better = "**tau form fixes it**" if a[1] > crit >= tv[1] else (
                "**both dependent**" if tv[1] > crit else "independent either way")
            print(f"| {name} | {n} | {a[0]:+.3f} | {a[1]:.1f} | {tv[0]:+.3f} | {tv[1]:.1f} | "
                  f"{tv[2]:.0f} | {better} |")
        continue

    print("\n`n_eff` is the variance-of-the-mean heuristic and is REPORTED, not applied. A series "
          "whose Q exceeds the critical value is one where an order-statistic bound computed from "
          "its raw n is optimistic, and by roughly the n/n_eff ratio shown.")


SECTIONS = {"cost": section_cost, "fit": section_fit, "ratios": section_ratios,
            "acf": section_acf, "drain": section_drain, "ceiling": section_ceiling,
            "control": section_control, "rates": section_rates}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("paths", nargs="+", help="log files or directories of *.log")
    ap.add_argument("--section", choices=sorted(SECTIONS), action="append",
                    help="only this section (repeatable); default is all")
    args = ap.parse_args(argv)

    sweep = load_sweep()
    logs, tx, samples, segs = collect(args.paths)
    if not tx and not samples and not segs:
        print("no `abr: tx` or `abr: sample` lines found — wrong logs, or the format moved "
              "and tests/run.py's regexes no longer match it.", file=sys.stderr)
        return 1
    print(f"<!-- generated by tools/abr-tx-report.py from {len(logs)} log(s): "
          f"{', '.join(os.path.basename(p) for p in logs)} -->\n")
    for name in (args.section or sorted(SECTIONS)):
        print(f"### {name}\n")
        SECTIONS[name](tx=tx, samples=samples, segs=segs, sweep=sweep)
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
